name: CI
on:
  workflow_dispatch:


  build image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        # name: Docker meta
        # id: meta
        # uses: docker/metadata-action@v3
        # with:
        #   images: |
        #     scanlidocker/chirpstack-application-server
        #   tags: |
        #     type=semver,pattern={{version}}
        #     type=semver,pattern={{major}}
        #     type=semver,pattern={{major}}.{{minor}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm/v7
          context: .
          push: true
          # tags: scanlidocker/chirpstack-application-server:v0.21
          # labels: ${{ steps.meta.outputs.labels }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}   